set nocompatible              " be iMproved

so ~/.vim/plugins.vim         " source Vundle stuff

syntax enable

let mapleader = ","           " set leader key to ',' (default '/')
let g:molokai_original = 1

set encoding=utf-8
set fileencoding=utf-8

set cursorcolumn              " set cursor column
set cursorline                " show current line
set nowrap                    " set nowrap
set ruler                     " show the line number on the bar
set autoread                  " watch for file changes
set number                    " activate line numbers
set hidden
set noautowrite               " don't automagically write on :next
set showmode
set showcmd
set nocompatible              " vim, not vi
set autoindent smartindent    " auto/smart indent
set smarttab                  " tab and backspace are smart

set linebreak
set cmdheight=2               " command line two lines high
set undolevels=1000           " 1000 undos
set noerrorbells              " No error bells please

set ignorecase                " Do case insensitive matching
set smartcase                 " except when using capital letters

filetype on                   " Enable filetype detection
filetype indent on            " Enable filetype-specific indenting
filetype plugin indent on

" Set tabs at 4 spaces
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim
set fillchars+=stl:\ ,stlnc:\

" FIX: PluginUpdate => git pull: git-sh-setup: No such file or directory in
" MacVim (OK in non-GUI version of Vim)
if has("gui_macvim")
    set shell=/bin/bash\ -l
endif

if has("gui_running")
    set listchars=tab:\|\
    highlight SpecialKey ctermfg=7 guifg=#363636 guibg=#363636
    set list!

    highlight CursorLine term=underline guibg=#333333  cterm=underline
    highlight CursorColumn term=underline guibg=#333333  cterm=underline

    " 80 columns: highlight column after 'textwidth', a red line.
    set columns=80
    set colorcolumn=+1 
endif

" use jk for esc
inoremap jk <ESC>


" toggle list mode
nmap <LocalLeader>tl :set list!<cr>

" toggle paste mode
nmap <LocalLeader>pp :set paste!<cr>

" edit .vimrc
nmap <Leader>ev :tabedit $MYVIMRC<cr>


" paste mode
set nopaste " Start in normal (non-paste) mode
set pastetoggle=<F2>
nnoremap <F2> :set invpaste paste?<CR>

" allow to save read-only files
cnoremap sudow w !sudo tee % >/dev/null

" setting backup dir
set backupdir=~/tmp
set completeopt=menu

" Set snipmate author name
let snips_author='Tonijs G. <hello@tonijs.com>'





"------------Visuals------------"
colorscheme kolor

set t_CO=256                  " force 256 colours for terminal vim
"set guifont=Fira\ Code:h14    " set gui font
set guifont=Inconsolata\ for\ Powerline:h15
set background=dark

set guioptions=               " remove gui options 
set guioptions=-e             " no gui tabs

set foldcolumn=2              " fold column width (left padding)
hi foldcolumn guibg=bg        " foldcoloumn bg
hi LineNr guibg=bg            " line nr bg

hi vertsplit guifg=bg guibg=bg







"------------Mappings------------"

" remove search highlighting
nmap <Leader><Space> :nohlsearch<cr>

" disabling arrow keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>
nnoremap j gj
nnoremap k gk

" Disabling help
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>



"------------Plugins------------"

"
" NERDTree
"

" Toggle NerdTree
nmap <D-1> :NERDTreeToggle<cr>
let NERDTreeHijackNetrw = 0 " allow -

let g:NERDTreeWinPos = "left"
let g:NERDTreeIgnore = ["\.pyc$"]
" let g:airline_powerline_fonts = 1

"
" CtrlP
"
"nmap <c-R> :CtrlPBufTag<cr>
nmap <c-e> :CtrlPMRUFiles<cr>

" ignore files / dirs
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows

let g:ctrlp_custom_ignore = 'DS_Store\|git'
let g:ctrlp_match_window = 'top,order:ttb,min:1,max:10,results:10'


"------------Split-management------------"
set splitbelow
set splitright

nmap <C-J> <C-W><C-J>
nmap <C-K> <C-W><C-K>
nmap <C-H> <C-W><C-H>
nmap <C-L> <C-W><C-L>




"------------Auto-Commands------------"

" auto source .vimrc on save
augroup autosourcing
    autocmd!
    autocmd BufWritePost .vimrc source %
augroup END





"------------Search------------"

set hlsearch                  " highlight searches
set incsearch                 " incremental search

